sonar.projectKey=JrinconRG_tallercontrol

sonar.organization=jrinconrg
sonar.host.url=https://sonarcloud.io

sonar.sources=src

sonar.tests=src

sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.test.jsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.config.js,**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info